Repository Orange-OpenSource/ods-charts, pull requests merged in 2023-12, with the labels that each got.

#9 chore(netlify): add Netlify script
  docs/index.html
  package.json
Labels: documentation, chore

#11 chore: manage relative path when running server locally
  docs/README.md
  docs/examples/index.html
  docs/index.html
Labels: fix

#19 chore: add Dependabot rules
  .github/dependabot.yml
Labels: chore, dependencies

#29 fix(test): In the third graph of the test test/html/, a legend is displayed under the title
  test/html/index.html
Labels: fix

#30 chore(deps): bump dependencies in `/test/angular-ngx-echarts`
  test/angular-ngx-echarts/package-lock.json
  test/angular-ngx-echarts/package.json
Labels: chore, dependencies

#45 fix(lib): displays axes for time series charts
  .github/PULL_REQUEST_TEMPLATE.md
  docs/examples/index.js
  docs/examples/multiple-line-chart.html
  src/theme/const/main-axis-type.const.ts
  src/theme/ods-chart-theme.ts
  src/theme/popover/ods-chart-popover.ts
  test/examples/timeseries-chart/index.html
  test/html/index.html
Labels: fix

#54 chore(deps): bump Angular from 17.0.6 to 17.0.7 for `test/angular*`
  test/angular-ngx-echarts/package-lock.json
  test/angular-ngx-echarts/package.json
  test/angular-tour-of-heroes/package-lock.json
  test/angular-tour-of-heroes/package.json
Labels: dependencies, examples

#55 chore(dev-deps): bump Node to 20.10.0
  .nvmrc
  test/react/package-lock.json
  test/vue/package-lock.json
Labels: dependencies

#61 chore(deps): bump Angular from 17.0.7 to 17.0.8 for `test/angular*`
  test/angular-ngx-echarts/package-lock.json
  test/angular-ngx-echarts/package.json
  test/angular-tour-of-heroes/package-lock.json
  test/angular-tour-of-heroes/package.json
Labels: dependencies, test
