Repository Orange-OpenSource/ods-charts, pull requests merged in 2024-12, with the labels that each got.

#412 feat(lib): Harmonize and simplify color objects
  docs/examples/index.js
  docs/use_cases/tooltip.html
  src/theme/css-themes/css-themes.ts
  src/theme/dark/ODS.categorical-colors.darker-tints.ts
  src/theme/dark/ODS.categorical-colors.functional.ts
  src/theme/dark/ODS.categorical-colors.lighter-tints.ts
  src/theme/dark/ODS.categorical-colors.purple.ts
  src/theme/dark/ODS.colors.blue.ts
  src/theme/dark/ODS.colors.categorical.ts
  src/theme/dark/ODS.colors.darker-tints.ts
  src/theme/dark/ODS.colors.functional.ts
  src/theme/dark/ODS.colors.green.ts
  src/theme/dark/ODS.colors.lighter-tints.ts
  src/theme/dark/ODS.colors.pink.ts
  src/theme/dark/ODS.colors.purple.ts
  src/theme/dark/ODS.colors.supporting-colors.ts
  src/theme/dark/ODS.colors.ts
  src/theme/dark/ODS.colors.yellow.ts
  src/theme/dark/ODS.sequential-colors.green.ts
  src/theme/dark/ODS.sequential-colors.purple.ts
  src/theme/dark/ODS.sequential-colors.yellow.ts
  src/theme/light/ODS.categorical-colors.darker-tints.ts
  src/theme/light/ODS.categorical-colors.pink.ts
  src/theme/light/ODS.categorical-colors.purple.ts
  src/theme/light/ODS.colors.blue.ts
  src/theme/light/ODS.colors.categorical.ts
  src/theme/light/ODS.colors.darker-tints.ts
  src/theme/light/ODS.colors.functional.ts
  src/theme/light/ODS.colors.green.ts
  src/theme/light/ODS.colors.lighter-tints.ts
  src/theme/light/ODS.colors.pink.ts
  src/theme/light/ODS.colors.purple.ts
  src/theme/light/ODS.colors.supporting-colors.ts
  src/theme/light/ODS.colors.ts
  src/theme/light/ODS.colors.yellow.ts
  src/theme/ods-chart-theme.ts
  test/angular-echarts/src/app/graph/graph.component.ts
  test/angular-echarts/src/app/line-chart/line-chart.component.ts
  test/angular-ngx-echarts/src/app/graph/graph.component.ts
  test/examples/bar-line-chart/index.html
  test/examples/single-line-chart/index.html
  test/examples/timeseries-chart/index.html
  test/html/index.html
  test/react/src/LineChartComponent.js
  test/vue/src/components/LineChartComponent.vue
Labels: feature, library

#421 Docs: Add a color mode switcher + a sticky header on all pages
  docs/assets/color-mode.js
  docs/assets/style.css
  docs/examples/bar-chart.html
  docs/examples/bar-line-chart.html
  docs/examples/donut-chart.html
  docs/examples/index.html
  docs/examples/index.js
  docs/examples/multiple-line-chart.html
  docs/examples/pie-chart.html
  docs/examples/single-line-chart.html
  docs/examples/stacked-bar-chart.html
  docs/images/ods-charts-icons.svg
  docs/index.html
  docs/use_cases/add-unit.html
  docs/use_cases/index.html
  docs/use_cases/index.js
  docs/use_cases/legends-holders.html
  docs/use_cases/size-management.html
  docs/use_cases/specify-color.html
  docs/use_cases/time-slider.html
  docs/use_cases/tooltip.html
  docs/use_cases/two-colors-serie.html
Labels: documentation, enhancement

#449 chore(deps): bump Angular deps from 18.2.12 to 19.0.4
  test/angular-echarts/package-lock.json
  test/angular-echarts/package.json
  test/angular-echarts/src/app/app.component.html
  test/angular-echarts/src/app/app.component.spec.ts
  test/angular-echarts/src/app/app.component.ts
  test/angular-echarts/src/app/graph/graph.component.ts
  test/angular-echarts/src/app/line-chart/line-chart.component.ts
Labels: dependencies

#448 docs(examples): Add availibility to choose between canvas and svg
  README.md
  docs/examples/index.js
Labels: documentation, examples
