Repository Orange-OpenSource/ods-charts, pull requests merged in 2024-02, with the labels that each got.

#116 chore(deps): bump the production and dev dependencies group in `/test/angular-ngx-echarts`
  test/angular-ngx-echarts/package-lock.json
  test/angular-ngx-echarts/package.json
Labels: dependencies, test

#117 chore(deps): bump the production and dev dependencies group in `/test/angular-echarts`
  test/angular-echarts/package-lock.json
  test/angular-echarts/package.json
Labels: dependencies, test

#109 Fix #101 about missing declaration file for module 'ods-charts'
  package.json
Labels: fix, library

#138 [Dependabot]: Better dependabot group approach
  .github/dependabot.yml
Labels: chore, dependencies

#141 chore(deps-dev): bump echarts from 5.4.3 to 5.5.0 in the lib and test…
  docs/examples/bar-chart.html
  docs/examples/bar-line-chart.html
  docs/examples/multiple-line-chart.html
  docs/examples/single-line-chart.html
  docs/examples/stacked-bar-chart.html
  package-lock.json
  package.json
  src/theme/popover/ods-chart-popover.ts
  test/angular-echarts/package-lock.json
  test/angular-echarts/package.json
  test/angular-ngx-echarts/package-lock.json
  test/angular-ngx-echarts/package.json
  test/react/package-lock.json
  test/react/package.json
  test/vue/package-lock.json
  test/vue/package.json
Labels: dependencies

#137 Build: Add script to bump copyright year
  build/bump-copyright-year.mjs
  package.json
Labels: enhancement, tools
