Repository Orange-OpenSource/ods-charts, pull requests merged in 2024-06, with the labels that each got.

#260 Fix three warnings when the documentation is generated (issue #211)
  src/ods-charts.ts
  src/theme/ODS.project.ts
  src/theme/ods-chart-theme.ts
Labels: documentation, fix

#242 Add Orange Design System look&feel to default Apache ECharts legends
  docs/examples/index.js
  src/theme/css-themes/css-themes.ts
  src/theme/legends/ods-chart-legends.ts
  src/theme/ods-chart-theme.ts
  src/theme/popover/ods-chart-popover.ts
Labels: feature, library

#275 docs: add precisions in readme
  README.md
Labels: documentation, enhancement
