Repository Orange-OpenSource/ods-charts, pull requests merged in 2024-04, with the labels that each got.

#191 chore(deps-dev): bump Node from 20.11.1 to 20.12.1
  .nvmrc
  test/angular-echarts/package-lock.json
  test/angular-ngx-echarts/package-lock.json
  test/react/package-lock.json
Labels: dependencies

#204 feat(lib): Availability to specify the colour at the serie level
  docs/use_cases/index.html
  docs/use_cases/specify-color.html
  src/theme/ODS.project.ts
  src/theme/legends/ods-chart-legends.ts
  src/theme/ods-chart-theme.ts
Labels: feature

#173 Docs: isolate charts in `<iframe>`s
  docs/examples/bar-chart.html
  docs/examples/bar-line-chart.html
  docs/examples/index.js
  docs/examples/multiple-line-chart.html
  docs/examples/single-line-chart.html
  docs/examples/stacked-bar-chart.html
Labels: enhancement

#214 chore(ci): add GitHub workflow to enforce Prettier check
  .github/workflows/lint.yml
Labels: enhancement, chore, tools

#217 Docs: Proposal to remove `lodash` import
  docs/examples/index.js
Labels: documentation
