Repository Orange-OpenSource/ods-charts, pull requests merged in 2024-03, with the labels that each got.

#107 Tooltip: First attempt to get tooltip in bounds anyway
  src/theme/ods-chart-theme.ts
  src/theme/popover/ods-chart-popover-definitions.ts
  src/theme/popover/ods-chart-popover.ts
Labels: fix, library

#147 Remove `tooltipConfine` option
  src/theme/popover/ods-chart-popover-definitions.ts
  src/theme/popover/ods-chart-popover.ts
Labels: enhancement, library

#159 Add an example of use of confine tooltip
  docs/index.html
  docs/use_cases/confine-tooltip.html
  docs/use_cases/index.html
  docs/use_cases/index.js
Labels: documentation, enhancement

#158 Bump Boosted to v5.3.3
  docs/examples/bar-chart.html
  docs/examples/bar-line-chart.html
  docs/examples/index.html
  docs/examples/index.js
  docs/examples/multiple-line-chart.html
  docs/examples/single-line-chart.html
  docs/examples/stacked-bar-chart.html
  docs/index.html
  docs/use_cases/confine-tooltip.html
  docs/use_cases/index.html
  src/theme/popover/ods-chart-popover-definitions.ts
Labels: chore, fix, dependencies

#136 Docs: Add analytics
  build/add_head.mjs
  docs/assets/tarteaucitron-config.css
  docs/assets/tarteaucitron-config.js
  docs/examples/bar-chart.html
  docs/examples/bar-line-chart.html
  docs/examples/index.html
  docs/examples/multiple-line-chart.html
  docs/examples/single-line-chart.html
  docs/examples/stacked-bar-chart.html
  docs/index.html
  docs/use_cases/confine-tooltip.html
  docs/use_cases/index.html
  docs/use_cases/two-colors-serie.html
  package.json
Labels: documentation, enhancement
